name: cat_tinder_hsse
description: A tinderâ€‘like app for cats ğŸ¾
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  http: ^1.2.0
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: ^4.19.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/icon.png
  adaptive_icon_background: '#F5F5F5'

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
